# Generated by Django 3.2.8 on 2022-12-02 13:02

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=register.models.image_file_name),
        ),
    ]
