# Generated by Django 3.2.8 on 2022-12-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='artists',
            field=models.ManyToManyField(blank=True, default=None, related_name='exhibitions', to='content.Artist'),
        ),
    ]
