# Generated by Django 4.1.3 on 2022-12-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_piece_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='artists',
            field=models.ManyToManyField(blank=True, default=None, related_name='pieces', to='content.artist'),
        ),
    ]
